### ISSUE TITLE
cannot load images on mac 

### ISSUE THREAD

**Issue by alexlib** [OpenPIV/openpiv_tk_gui#1]

**Comment by eguvep** [comment]
"Cannot load" means, "they do not show up in the file-list" or "they are not displayed"? Do you get an error message, if you run OpenPivGui from the command-line?

**Comment by alexlib** [comment]
The error message is 

`Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/alexliberzon/opt/miniconda3/envs/openpivgui/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "openpivgui/OpenPivGui.py", line 105, in start_processing
    mp = MultiProcessing(self.p)
  File "/Users/alexliberzon/opt/miniconda3/envs/openpivgui/lib/python3.7/site-packages/openpivgui/MultiProcessing.py", line 62, in __init__
    'Please provide an equal number of A and B images.')
ValueError: Please provide an equal number of A and B images.`

After I select images and press `start chain`

**Comment by eguvep** [comment]
Presumably, the file list did not contain image links at all, or an uneven number of links.

**Comment by alexlib** [comment]
I select your set of images - these are pairs of a,b

**Comment by eguvep** [comment]
Did you accidentally also select the README.md file in the same directory? You can press the »back« and »forward« button below the listbox once, to let OpenPivGui filter the directory content automatically.

**Comment by alexlib** [comment]
no I didn't. even if I choose only the first pair, same issue.

**Comment by eguvep** [comment]
Mmmh, is there something unusual in the pathnames, like quotation marks or spaces?

**Comment by alexlib** [comment]
The problem on my screen is that the most right list of the vectors was "outside of the visible region" and therefore - without clicking on the images or the vector files it wasn't processing them.

**Comment by eguvep** [comment]
Ah - Interesting! The GUI should not start in a way that parts of it are outside the screen. i told the root widget to start with width=screen_width next time. Use `pip3 install update openpivgui` for the latest version. I also included more validation methods and plotting types.

**Comment by alexlib** [comment]
i updated, but it didn't help - the file list is still outside on the right side :)

**Comment by eguvep** [comment]
I can only guess, because i don't have a Mac at hand: Is there a widget, that renders very wide on Mac OS? For example the input field (entry) for the navigation pattern on the General-Rider? Does the GUI look very different from the Screen shot:https://raw.githubusercontent.com/OpenPIV/openpiv_tk_gui/master/fig/open_piv_gui_vector_plot.png?

**Comment by alexlib** [comment]
![image](https://user-images.githubusercontent.com/747110/79136905-6e87bd00-7dba-11ea-89c2-d6230d98d61c.png)

**Comment by alexlib** [comment]
maybe it's better to move to the panels one behind another and not next to each other? 
any attempt to resize the window causes the right panel with the list of files to collapse and I cannot find it anymore. Only if I pan the whole window to the left, then I see the list on which I can click.

**Comment by alexlib** [comment]
or maybe to have the list on the left - so it's at least half visible

**Comment by eguvep** [comment]
Now I see! I moved the buttons to the top frame border. I hope, this gives enough room for the file list. Otherwise I have to rethink the layout... I anyway should record the introduction video again, with the changed layout ;-)

**Comment by alexlib** [comment]
it's better now :) thanks
