### ISSUE TITLE
Possible cluttering of preprocessing

### ISSUE THREAD

**Issue by ErichZimmer** [OpenPIV/openpiv_tk_gui#14]
Dear Mr. Vennemann,

I am finishing up preprocessing and I think I may have went too far. To me, it looks very cluttered with some features present that most will probably not use. Additionally, it kind of looks painful to my eyes, but that's what I think. What is your opinion?

![one_big_preproccess](https://user-images.githubusercontent.com/69478071/93279325-92499780-f78c-11ea-9b53-0b6f1f55fec1.JPG)

Regards,
Erich Zimmer

PS, I added custom image sequencing so the user could choose anything from (1+2),(2+3) to (1+8),(2+9). I will be commiting/pushing it after some more validation that it works as promised.

**Comment by eguvep** [comment]
Dear Erich,

To me, it does not look so bad. Your screenshot appears to me as a clear, one dimensional list, that users  can walk through from top to bottom.

One thing, you may think about, is to introduce a second rider for pre-processing: You could leave masking and ROI on the first one, and collect all filters on the second one. That would be a bit of work to renumber all the indices in OpenPivParams, but not a real problem. We should not forget about correcting the constants from line 108 on in that case.

Another thing, we could think about, is an additional type or keyword in the OpenPivParams class, that creates a label and a horizontal line for optically grouping parameters that belong together.

Other options, are not so suited, I think:

A (widespread) alternative is to hide settings in sub menus and pop up windows behind buttons called Detailed Settings / Expert Settings / Special Settings / Very Special Expert Settings ;-) This would just hide complexity and would also clutter the code, and thus contradicting another important design criterion of OpenPivGui: Write clear, concise and simple code.

A second alternative is to place the widgets in a 2D manner. But that would also not help a lot and would in turn make the code more complex.

Peter

**Comment by eguvep** [comment]
Custom frequencing a very cool option, by the way! Like in JPIV! Thanks for that, already!

**Comment by eguvep** [comment]
...you could also have riders like 'filters 1' and 'filters 2', with frequently used filters collected on the first, less frequently used filters collected on the second tab. What do you think?

**Comment by ErichZimmer** [comment]
Dear Mr. Vennemann,

I took your suggestions and tried them with pretty decent success. I split the preprocessing into two different tabs while keeping everything in the 'PREPROC' index. I think it looks visually better this way as all the more frequently used preprocessing functions are placed in the first tab. Here is what I got so far (also included the custom image frequencing).

![General](https://user-images.githubusercontent.com/69478071/93411533-f76ebd00-f860-11ea-9675-86bd730b5463.JPG)

![Preprocess1](https://user-images.githubusercontent.com/69478071/93411603-1ff6b700-f861-11ea-8903-4b3504c405a3.JPG)

![Preprocess2](https://user-images.githubusercontent.com/69478071/93411644-38ff6800-f861-11ea-9806-15e1f8520353.JPG)


For the newer filters I added, a significant bug was found. All images arrays had to be converted to int32 to allow the filters to work properly (especially float64). The background subtraction derived from averaging of images was not working properly due to my limited experience with python and numpy (getting better though ;)). Another major bug was found in the image frequencing when the skip was set to greater than one. The last few .vec files were not calculated properly and caused all values to be nans. I created a simple equation that forecasts the amount of 'interesting' correlations which is skip - step where skip is larger than or equal to step. I'm not sure what is going on here, but I may add this to the script used to sort the images in multiprocessing to remove those last few arrays. Other than that, that is the only setbacks I manage to find so far. Hopefully, the PIV book by Raffel et. al. (2007) and articles by Westerweel and Scarano et. al. (2005) will help me on my journey of particle image/shadow velocimetry.

Regards,
Erich ZImmer

**Comment by ErichZimmer** [comment]
Dear Mr. Vennemann,

I took your suggestions and tried them with pretty decent success. I split the preprocessing into two different tabs while keeping everything in the 'PREPROC' index. I think it looks visually better this way as all the more frequently used preprocessing functions are placed in the first tab. Here is what I got so far (also included the custom image frequencing).

![General](https://user-images.githubusercontent.com/69478071/93411533-f76ebd00-f860-11ea-9675-86bd730b5463.JPG)

![Preprocess1](https://user-images.githubusercontent.com/69478071/93411603-1ff6b700-f861-11ea-8903-4b3504c405a3.JPG)

![Preprocess2](https://user-images.githubusercontent.com/69478071/93411644-38ff6800-f861-11ea-9806-15e1f8520353.JPG)


For the newer filters I added, a significant bug was found. All images arrays had to be converted to int32 to allow the filters to work properly (especially float64). The background subtraction derived from averaging of images was not working properly due to my limited experience with python and numpy (getting better though ;)). Another major bug was found in the image frequencing when the skip was set to greater than one. The last few .vec files were not calculated properly and caused all values to be nans. I created a simple equation that forecasts the amount of 'interesting' correlations which is skip - step where skip is larger than or equal to step. I'm not sure what is going on here, but I may add this to the script used to sort the images in multiprocessing to remove those last few arrays. Other than that, that is the only setbacks I manage to find so far. Hopefully, the PIV book by Raffel et. al. (2007) and articles by Westerweel and Scarano et. al. (2005) will help me on my journey of particle image/shadow velocimetry.

Regards,
Erich ZImmer

PS, I hope this comment is alright due to internet download speeds <10 Kb/sec.

**Comment by ErichZimmer** [comment]
Dear Mr. Vennemann,

I took your suggestions and tried them with pretty decent success. I split the preprocessing into two different tabs while keeping everything in the 'PREPROC' index. I think it looks visually better this way as all the more frequently used preprocessing functions are placed in the first tab. Here is what I got so far (also included the custom image frequencing).

![General](https://user-images.githubusercontent.com/69478071/93411533-f76ebd00-f860-11ea-9675-86bd730b5463.JPG)

![Preprocess1](https://user-images.githubusercontent.com/69478071/93411603-1ff6b700-f861-11ea-8903-4b3504c405a3.JPG)

![Preprocess2](https://user-images.githubusercontent.com/69478071/93411644-38ff6800-f861-11ea-9806-15e1f8520353.JPG)


For the newer filters I added, a significant bug was found. All images arrays had to be converted to int32 to allow the filters to work properly (especially float64). The background subtraction derived from averaging of images was not working properly due to my limited experience with python and numpy (getting better though ;)). Another major bug was found in the image frequencing when the skip was set to greater than one. The last few .vec files were not calculated properly and caused all values to be nans. I created a simple equation that forecasts the amount of 'interesting' correlations which is skip - step where skip is larger than or equal to step. I'm not sure what is going on here, but I may add this to the script used to sort the images in multiprocessing to remove those last few arrays. Other than that, that is the only setbacks I manage to find so far. Hopefully, the PIV book by Raffel et. al. (2007) and articles by Westerweel and Scarano et. al. (2005) will help me on my journey of particle image/shadow velocimetry.

Regards,
Erich ZImmer

PS, I hope this comment is alright due to internet download speeds <10 Kb/sec.

**Comment by eguvep** [comment]
You are right, it is not at all necessary to reindex the parameters! – Very good! Looks perfect for me.
Raffel is good for quickly getting started, Westerweel for a deeper understanding. I would recommend reading them in this order. I think, I can close this issue, right?
