### ISSUE TITLE
Upadate Layout without restart

### ISSUE THREAD

**Issue by eguvep** [OpenPIV/openpiv_tk_gui#17]
Offer different layouts for small and larger screens. Switch layout without restart.

**Comment by eguvep** [comment]
...lower priority, since there is a new layout for almost all screen sizes underway.

**Comment by ErichZimmer** [comment]
For future reference, the tkinter .config() function is a good way to update the GUI configuration without restarting.

**Comment by eguvep** [comment]
With version v0.4.11 the GUI is rebuild, as soon as an add-in got selected or deselected (File → Select Add-Ins.
