### ISSUE TITLE
Add horizontal scroll bar in files menu

### ISSUE THREAD

**Issue by eguvep** [OpenPIV/openpiv_tk_gui#18]
The arrow key also shifts long path-names, but not all users are aware of it.

**Comment by ErichZimmer** [comment]
Dear Prof. Vennemann,

I added a horizontal scroll bar, but it doesn't have the same visual effects as the vertical scroll bar. Other than that, it works really well and want to make sure it is what you want before I finish everything up for a pull request.

![Horizontal_scrolbar](https://user-images.githubusercontent.com/69478071/97650597-0df36100-1a28-11eb-9128-823908bd1038.JPG)

Kind regards,
Erich Zimmer

**Comment by eguvep** [comment]
Is the horizontal scroll bar scrolling, though?

**Comment by ErichZimmer** [comment]
The horizontal scroll bar does scroll. It just doesn't have any animations/visual effects. It works really well and is pretty useful as, like you mentioned above, most users don't know the arrow keys also scroll.

**Comment by alexlib** [comment]
what is the flow in the image @ErichZimmer ? I'd like to analyse that :)

**Comment by eguvep** [comment]
> The horizontal scroll bar does scroll. It just doesn't have any animations/visual effects. It works really well and is pretty useful as, like you mentioned above, most users don't know the arrow keys also scroll.

Ok! Fine! So we can close this issue, right? Thanks for fixing that!

**Comment by ErichZimmer** [comment]
@alexlib 
If I remember right, the images is from the  4th international PIV Challenge case B. There should be 1144 PIV images with the size of 1280 x 800. The image of the results above was me testing the region of interest cropping with two different data sets; hence the larger amount of PIV images.
