### ISSUE TITLE
installation instructions

### ISSUE THREAD

**Issue by alexlib** [OpenPIV/openpiv_tk_gui#2]
Do I have to install openpiv-python first?

**Comment by eguvep** [comment]
The PIP configuration file "setup.py" contains the line "install_requires='OpenPiv'". PIP should therefore pull openpiv-python and its dependencies automatically. This has been tested on Ubuntu-Linux 18.04 and a Debian GNU/Linux 10 cluster. In both cases this worked fine.

**Comment by alexlib** [comment]
Need to update the pip more often. Presently it installs somewhat older version.
