### ISSUE TITLE
Refactoring windef.py - is it a good idea at all? 

### ISSUE THREAD

**Issue by alexlib** [OpenPIV/openpiv_tk_gui#20]
I think we need to refactor windef.py - it has many duplicate functions with tools.py and pyprocess.py and I also think it is less convenient to have it a monolithic function (with piv() underneath...). But before I break everything - how would it affect the GUI? 

Actually what I want to do is to follow your way:
https://github.com/OpenPIV/openpiv_tk_gui/blob/d9f9d891735e63d65c209b9dcefc470f24d8306f/openpivgui/MultiProcessing.py

**Comment by eguvep** [comment]
It is not completely clear to me, what you are planning to change. But, nevertheless, I think, it will not be a big deal for the GUI.

From `openpiv.windef` we just call two functions directly:

- `first_pass`, and later in a loop
- `multipass_img_deform` for all other passes.

I see two options:

1. You leave those two functions as entry points. So nothing changes for the GUI.
2. At the moment, every user of windef.py does the filtering between the passes and looping over the passes him- or herself. If you plan to provide a clean function like `windef.do_correlation(parameters)` or so with something like the content of the if-block from the following line on up to the end of the file https://github.com/OpenPIV/openpiv_tk_gui/blob/d9f9d891735e63d65c209b9dcefc470f24d8306f/openpivgui/MultiProcessing.py#L221
we would just replace that if-block by a call of that new function.

But there is a chance, that I completely misunderstand you ;-)

**Comment by alexlib** [comment]
Thanks, you got the point right. In openpiv-python windef is presented now as a monolithic `windef.piv(settings)` which is like `windef.do_correlation(parameters)` you mention, and not through the separate calls to `first_pass` and then `multiplass_img_deform`. I want to do refactor the code itself a bit (make comments instead of strings, clean duplications with openpiv-python `tools` and other modules) and also make a demo where the user can apply separate steps using entry points and not in a single shot. 

Furthermore, there is a `circular` vs `linear` correlation functions, this requires to become a global openpiv-python function and probably move to the `process.pyx` or similar. Do you use those ?

**Comment by ErichZimmer** [comment]
Dear Prof. Liberzon,

**circular vs linear**
I am not sure if this adds any value, but here is my take. I personally use both depending on how noisy the images are. For low noise, high quality images, I always use circular correlation. However, when I evaluate noisy low/medium quality images, I mostly use linear correlation for the added robustness. In my opinion, the added accuracy of linear correlation outweighs the additional computation costs and slower correlation speeds and is really helpful when trying to get the best out of a homemade PIV system. So if we remove linear correlation, this might have some negatives. 

If global functions are to be avoided, maybe an if statement can be placed inside of the 'first_pass' and 'multipass_img_deform' with an additional parameter added into the function. 

Kind regards,
Erich Zimmer 

P.S. How do you highlight words like in the post above? I can't seem to find it and my internet isn't cooperating to well. :(

**Comment by alexlib** [comment]
See markdown for github @ErichZimmer

**Comment by eguvep** [comment]
Ok, now I see clearer – thanks! I didn't use the monolithic function, because I wanted to use our `OpenPivParams` object directly. It would have been an additional step to generate a `windef.Settings` object and parameterize it.

So I conclude:

- The changes do not affect the GUI at all, because we just use `first_pass` and `multiplass_img_deform`.
- We use both, `circular` and `linear` correlation, but would prefer keeping at least `linear` (Thanks @ErichZimmer!)

The monolithic function is still useful, when running `windef.py` as a script.

A PEP and Sphinx conform documentation is always good, of course! Thanks for the initiative, @alexlib!

So I think, we can close this issue, right?
