### ISSUE TITLE
releases on github or pypi badge

### ISSUE THREAD

**Issue by alexlib** [OpenPIV/openpiv_tk_gui#21]
I see the PyPI is updated to 0.3.9, but it's difficult to know about the latest version if you don't create releases and don't use badges with the pypi version. 
Probably it has also to state which version of openpiv-python it reflects. there will be unlucky situations where one of the versions will not match another. 

For instance when I run now `pip install openpivgui --upgrade` I get 0.3.9 with the icon bug, when I run `pip install git+https://github.com/openpiv/openpiv_tk_gui` I get 0.3.8 (and it's also the label in the window 0.3.8) and the icon problem disappears.

**Comment by eguvep** [comment]
Thanks for pointing this out! This happens, when first pushing to Github and then packing and uploading to PyPI. The PyPI package on Gitub remains at the previous version in this case. I've set up a Github-Action for packaging and uploading to PyPI now, so different version numbers should not happen again.

Another thing is the nasty icon image bug, that seemed to reappear. I fixed that again.
