### ISSUE TITLE
Internal Data Format

### ISSUE THREAD

**Issue by eguvep** [OpenPIV/openpiv_tk_gui#22]
# Background

There is a discussion about the internal data format of the GUI, spread over different posts. I summarize it here, to proceed and finalize the discussion in one place.

# Status quo

Correlation results are saved in simple space separated text files of the following format:
```
x  y  vx  vy  p2n
16 16 4.5 8.2 2134
32 16 3.8 7.5 2989
...
```
Post processing results are saved in additional files, with a postfix in the filename. Users navigate through the project by filtering the directory content according to the postfixes and file extensions.

Advantages:

- human readable format
- smallest common denominator of most software including terminal applications like `awk`
- follows UNIX [design philosophy](https://en.wikipedia.org/wiki/Unix_philosophy#Mike_Gancarz:_The_UNIX_Philosophy) ’Store data in flat text files.'

# Saving results in a dictionary

[first original post](https://github.com/OpenPIV/openpiv_tk_gui/pull/19#issuecomment-707279552)
[second original post](https://github.com/OpenPIV/openpiv_tk_gui/pull/19#issuecomment-725865531)

proposed format:

Let 'i' equal the index key number for a data set.
[i][0] = x array
[i][1] = y array
[i][2] = raw u array
[i][3] = raw v array
[i][4] = signal to noise ratio
[i][5] = typevector (if values were marked NaN or interpolated)
[i][6] = mask (for areas to not be analyzed/interpolated)
[i][7] = postprocessed u array
[i][8] = postprocessed v array

The arrays are appended in the MultiProcessing class at the end of each iteration. Each index key could be saved as a .vec or .txt file in standard 'x, y, u, v, typevector (mask)' format. In postprocessing, the u and v results are appended as well as the typevector (mask).

Advantages:

- Allows the whole session (excluding image pairs) to be saved and exported.
- Listbox will show dictionary key and closely relate original and postprocessed data.
- Results can still be saved in standard format.
- preprocessing/postprocessing of each frame individually or control how many frames to evaluate
- customize how the results should be saved and exported. 
- allowing database-like system like .npz files (NumPy write/read functions)

# Other possible formats

- NetCDF
- Pandas DataFrame
- [xarray](https://github.com/pydata/xarray)
- HDF5

**Comment by eguvep** [comment]
# Discussion

**Comment by eguvep** [comment]
# Discussion

## Which format?

Two formats do not introduce further dependencies: 

- The native python dictionary, and 
- the pandas dataframe (because we anyway use pandas dataframes, already).

Handling of both formats is simple and well known by virtually all python users.

Because of this reasons, I would prefer one of these two formats over the other ones (NetCDF, HDF5, xarray, a new class, ...).

## Navigation

I think, the navigation by filtering filename postfixes and extensions was kind of simple, but would be obsolete in case of using a dictionary. What do you  think, @ErichZimmer, could the images, raw evaluations and post processed files be displayed in a tree like structure in the list frame on the right? What do you think of using a `tkinter.ttk.TreeView`?

## Skript Structure

I think we need a default definition of the dictionary (e.g. name of the keys) and a converter between formats (starting with the default cvs format).

[Here](https://github.com/OpenPIV/openpiv_tk_gui/pull/19#issuecomment-711745314) we already discussed, that it might be beneficial to follow the UNIX philosophy:

- Write programs that do one thing and do it well.
- Write programs to work together.
- Write programs to handle text streams, because that is a universal interface.

In that sense, I would suggest to **provide a new module** or class **that is doing the conversion** of any PIV format into any other PIV format. This should be a new project (your project @ErichZimmer?) **in the main project path**. It should not be part of the GUI, because it is independently usable working code. The GUI should just import it. What do you think, @alexlib?

**The default dictionary should be part of the GUI**, because at the moment, I can not see any use in another part of the OpenPIV project. It could just be a module in the openpivgui hierarchy.

**Comment by ErichZimmer** [comment]
Dear Prof. Vennemann,

I made an attempt to allow the preprocessing of individual frames while complying with the UNIX philosophy and ended up with this. The GUI remains practically the same except a dictionary is created to save the preprocessing settings of each image pair. So, we end up with the UNIX philosophy, a dictionary containing information on how to process images, and a pandas data frame to load the results and plot them. Each PIV result can be individually processed too by creating a new postprocessed file and writing/rewriting it in a similar way as appending or modifying a portion of a dictionary. In total, three types of files are created;  settings used (a single file for now), raw results, and processed results (with postprocessed settings placed in the settings file). This completely removed the issue of slow loading speeds with large processing sessions. Additionally, a function can load the settings saved in the file and allow the software to process the images exactly the same way as before. To minimize the number of files produced, the settings dictionary is saved into a npz file (not human readable to increase speed, but could be changed to txt file and human readable pretty easy). When I get time to get on a computer and properly explain this (going off by memory right now), I'll make a more detailed explanation. 

Regards,
Erich Zimmer

**Comment by alexlib** [comment]
I vote for simplicity.

**Comment by eguvep** [comment]
Dear Erich,
Just to confirm: The main benefit is, that everything can be stored together: parameters used, images, preprocessed images, raw vector data and post processed vector data? 
Because reproducability is good scientific practice, I would much appreciate this concept!
Simplicity is granted by just using an »ordinary« python dictionary.
Please take care by design, that new OpenPivGui versions will always be compatible to parameters stored by previous OpenPivGui versions. At least in a sense, that old dictionaries can still be loaded without crashing something. At the moment, this is granted by first loading the actual parameter template and then only copying parameters from the users home directory that  are still used and valid.
Regards!
Peter
PS: I am fine with »Dear Peter« ;-)

**Comment by ErichZimmer** [comment]
Dear Peter,

For now, I will be keeping the GUI the same and simply enhance it. The main theme established by you is to keep the GUI simple, short, and concise. With that in mind, I'll halt my developments on more complicated/sophisticated GUIs and leave it as my personal experimental software.

Regards,
Erich Zimmer

PS; thanks for letting me know about rewriting my starting statement (Dear ...). Google isn't very helpful at times and sometimes gives you the wrong answer due to user error.

**Comment by ErichZimmer** [comment]
Dear Peter,

I am finalizing the enhancements again and pushed a semi-finished GUI. Do you know if you can go into my branch and test it to see if you like the changes?

Thanks,
Erich Zimmer

**Comment by eguvep** [comment]
Yes, I can pull from your branch and test the version locally. I hope, I have time for that tomorrow!

**Comment by eguvep** [comment]
Dear Erich,

**Test**
I tested your branch (quickly). I think it is working properly. Thanks for implementing the progress bar!
One thing: Before processing the images, the routine checks, if the file extension is in a file extension list. That list is not complete. PGM is missing, for example. We also should not test case sensitive. Use `str.upper()` or so. You can just start another pull request.

**Internal file format**
I was already convinced by your argumentation! But ok. we can postpone that. I also have the impression, that the GUI is getting more attention at the moment. So I would recommend to focus on testing, debugging and documentation rather than on implementing new features for a while. What do you think? We should also reformat the code to PEP 8 standard. I will write an issue about that.

Regards!

Peter

**Comment by eguvep** [comment]
I think, I close this issue. We can reopen it, in case we return to the internal file format discussion.

**Comment by ErichZimmer** [comment]
Dear Peter,

I added individual image processing to the GUI in a new branch `GUI_enhancements2`. A lot of work needs to be done, but it is mostly a fully functional system and appears to work efficiently enough. Additionally, the file filter still works like normal except that when images are listed, only the images originally selected are shown. Sorry if I am too vague/don't make sense, I am starting my 47 week long military training tomorrow (also spent 13 hours today to get the GUI in a solid state 😄 ), which also means that I won't be able to contribute during that time period. :(

Regards,
Erich Zimmer

**Comment by alexlib** [comment]
Thanks a lot @ErichZimmer and good luck with your service

**Comment by eguvep** [comment]
Oh dear, thats almost a year! Hope, this will be a good time for you! Thanks a lot for all your very helpful ideas and contributions! – Take care, @ErichZimmer!
