### ISSUE TITLE
No select files button available

### ISSUE THREAD

**Issue by barbeti** [OpenPIV/openpiv_tk_gui#25]
Dear everyone before switching to a 100% script strategy, I have tried to use the Tkinter GUI in order to process
rapidly my images. 
When I open the GUI, I don't have the **select files** button in the navigation bar. 
Hence, I've tried to select my files from the **open directory** button, but my png files are not visible by the GUI

The screenshots are attached.
![image](https://user-images.githubusercontent.com/75028532/100247582-77bc3900-2f08-11eb-928e-6ad7fc40fc47.png)
![image](https://user-images.githubusercontent.com/75028532/100247789-b6ea8a00-2f08-11eb-837c-311ec9e7df43.png)

The problem is that I can't follow the eight minutes video tutorial about the Tkinter GUI of OpenPIV, I can't upload my PNG files.

By advance thanks - Tim

**Comment by eguvep** [comment]
Dear Tim,

Thanks for commenting! Just open the directory. The png files in the directory will automatically be listed in the files-frame on the right of the GUI. You can click the »back« and »forward« buttons to filter the directory for other file formats, if there are any. Click on one of the links in the files-frame to display the image. Use the right arrow key for horizontal scrolling.

In the next version, the help will be corrected and there will be a horizontal scrollbar in the files-frame.

Did this solve the issue?

Regards,

Peter

**Comment by barbeti** [comment]
Many thanks Peter Venneman, your advice solves my issue.
I think that now I have to look down the documentation.

Depending which evaluation method I used I have remarked that a certain amount  of photos is required to start processing.

Again thanks - Tim

________________________________
De : Peter Vennemann <notifications@github.com>
Envoyé : mercredi 25 novembre 2020 16:57
À : OpenPIV/openpiv_tk_gui <openpiv_tk_gui@noreply.github.com>
Cc : barbeti <tim.nageurpro@hotmail.fr>; Author <author@noreply.github.com>
Objet : Re: [OpenPIV/openpiv_tk_gui] No select files button available (#25)


Dear Tim,

Thanks for commenting! Just open the directory. The png files in the directory will automatically be listed in the files-frame on the right of the GUI. You can click the »back« and »forward« buttons to filter the directory for other file formats, if there are any. Click on one of the links in the files-frame to display the image. Use the right arrow key for horizontal scrolling.

In the next version, the help will be corrected and there will be a horizontal scrollbar in the files-frame.

Did this solve the issue?

Regards,

Peter
