### ISSUE TITLE
please update the GUI to comply with the 0.23.2 version of openpiv

### ISSUE THREAD

**Issue by alexlib** [OpenPIV/openpiv_tk_gui#26]
@eguvep it fails on my new Linux installation 
```
(openpivtkgui) user@Turbo-NUC7:~/Downloads/repos/openpiv-python$ python -m openpivgui.OpenPivGui
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/openpivtkgui/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/user/miniconda3/envs/openpivtkgui/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user/miniconda3/envs/openpivtkgui/lib/python3.8/site-packages/openpivgui/OpenPivGui.py", line 54, in <module>
    from openpivgui.MultiProcessing import MultiProcessing
  File "/home/user/miniconda3/envs/openpivtkgui/lib/python3.8/site-packages/openpivgui/MultiProcessing.py", line 23, in <module>
    import openpiv.process as piv_prc
ModuleNotFoundError: No module named 'openpiv.process'
```

**Comment by alexlib** [comment]
replacing `import openpiv.process` with `import openpiv.pyprocess` solves the issue at least it opens the GUI

**Comment by alexlib** [comment]
and as expected many things fail as well. sorry but it seems to be a lot of work. I experienced so far 
1.`piv_wdf.multi_process` returns only 5 variables (no mask anymore, it's not included in multipass
2. `read_csv` fails to read the .vec file after that.

**Comment by eguvep** [comment]
I will return on that issue as soon as possible. We are returning to 100 % e-teaching at our university, so I am too busy to solve the issue immediately.

**Comment by ErichZimmer** [comment]
Dear Alex and Peter,

I fixed this issue in a recent pull request (accidentally merged it into upstream instead of local fork).

Regards,
Erich Zimmer

**Comment by eguvep** [comment]
Dear Erich,
thanks a lot – it is very good, that you merged upstream, because my time is very limited at the moment and fixing that issues was really overdue. Is everything working? In that case, we could tag it a release and get it packed and uploaded to PyPI automatically. Thanks again for devoting parts of your Christmas-holidays for OpenPIV!
Regards!
Peter
