### ISSUE TITLE
GUI needs update for new OpenPIV version

### ISSUE THREAD

**Issue by ErichZimmer** [OpenPIV/openpiv_tk_gui#29]
I frankly won't have time to fixt the GUI anymore. Maybe someone else can fix it?

Reported issue:
https://groups.google.com/g/openpiv-users/c/qlTqedpAgeE

Regards,
Erich Zimmer

**Comment by eguvep** [comment]
Thanks for devoting your Christmas-break for OpenPIV! I'll have time for the GUI from February on.

**Comment by ErichZimmer** [comment]
Dear Peter,
On my fork, I have a branch that has a prototype version with interactive masking and region of interest labeled something like "GUI_2.0_prototype". There are some nice tricks that can be learned from it. Sadly, I ran out of time before I could get it fully functional :(, but again, there much that can be learned from it.

Regards,
Erich Zimmer

Written using Outlook

**Comment by alexlib** [comment]
> Dear Peter, On my fork, I have a branch that has a prototype version with interactive masking and region of interest labeled something like "GUI_2.0_prototype". There are some nice tricks that can be learned from it. Sadly, I ran out of time before I could get it fully functional :(, but again, there much that can be learned from it. Regards, Erich Zimmer Written using Outlook

Thanks for all the difficult work. It's always like this - an intermittent and great peaks of development with long breaks :) You did a lot of good stuff, hopefully we'll be able to pick it up.

**Comment by alexlib** [comment]
> I frankly won't have time to fixt the GUI anymore. Maybe someone else can fix it?
> 
> Reported issue:
> https://groups.google.com/g/openpiv-users/c/qlTqedpAgeE
> 
> Regards,
> Erich Zimmer

I suggest to use meanwhile `openpiv==0.23.3` in the `setup.py` to avoid the bug

**Comment by alexlib** [comment]
Workaround

`pip install https://github.com/openpiv/openpiv_tk_gui/archive/openpiv_0.23.3.zip`

**Comment by eguvep** [comment]
Thank you guys for the progress and the workaround! I am busy with home-schooling of three small children due to COVID lockdown. I will return to OpenPIV as soon as possible.

**Comment by eguvep** [comment]
Fixed.
