### ISSUE TITLE
OpenPivGui Python processing issue

### ISSUE THREAD

**Issue by PAMPA-1996** [OpenPIV/openpiv_tk_gui#31]
Hi,
I am using OpenPIVgui python 0.4.1 in my Windows 10. But each time it is showing that failed to process.

I used earlier the open piv python source code with the same images. But it was working. 
Is there any issue with my pc or anything else?

I am getting this error.
"PIV evaluation thread stopped.first_pass() got an unexpected keyword argument 'normalized_correlation'."

**Comment by alexlib** [comment]
1. how do you installed python? is it anaconda installation? 
2. if it's anaconda or miniconda installation, please try the following: 

1. new conda environment : `conda create -n openpivgui python=3.7` and say yes to all the questions
2. activate conda environment `conda activate openpivgui`
3. in the new environment install again the openpivgui using the previous working version:
4. `pip install https://github.com/openpiv/openpiv_tk_gui/archive/openpiv_0.23.3.zip`

please report the errors along these 5 steps with screenshots so we understand better the problems.

**Comment by PAMPA-1996** [comment]
Hi,

I am again getting errors after following these steps.
Sharing the screenshots of the consecutive steps.

**Comment by eguvep** [comment]
I just adapted the OpenPivGui to openpiv v0.23.4. Can you upgrade and check, whether everything is now working?
`pip3 install --upgrade --no-cache-dir openpivgui`

**Comment by PAMPA-1996** [comment]
Yes, I have upgraded the version Simple OpenPIV 0.4.2
I'm getting the error, Using these two images.
"PIV evaluation thread stopped. [Errno 13] Permission denied:
'C:/Users/image\\vec_piv_FFT_0.vec'"

**Comment by eguvep** [comment]
Hmm, strange, where are those single slashes coming from? We use the following code to generate the filename:
```
basename = 'vec'
postfix = '_piv_FFT_'
count = 0
num = str(count)
os.getcwd() + os.sep + basename.split('.')[0] + postfix + num + '.vec'
```
On Windows, that should generate:
```
C:\\Users\\image\\vec_piv_FFT_0.vec
```
(It does, I just tested that on a virtual machine.)
On other OS, it gives something like:
```
/home/peter/image/vec_piv_FFT_0.vec
```

**Comment by PAMPA-1996** [comment]
I am doing these steps:
Import images.
Windowing
Analysis.
Start processing.
After sometime gives failed to do PIV analysis and giving this error. My
PIV_GUI is different from video tutorial PIV_GUI.

**Comment by eguvep** [comment]
I just tested v0.4.2 on a fresh virtual windows installation, and the evaluation works fine.

![Bildschirmfoto von 2021-02-27 15-38-09](https://user-images.githubusercontent.com/58531020/109390462-12665280-7912-11eb-88bd-ac100f5f9700.png)

You may try to follow these steps:

- close the GUI
- find the file open_piv_gui.json in your home directory and remove it
- restart the GUI

Does that help?

**Comment by alexlib** [comment]
do you run it in VirtualBox?
maybe we could share somewhere a complete image that runs?

**Comment by eguvep** [comment]
No, on a virtual infrastructure at my university. The virtual machines are reset at every login. I just typed `pip3 install openpivgui` and everything worked. It should be that simple.

**Comment by PAMPA-1996** [comment]
I tried with the following steps.but same error is coming.

I used pip instead of pip3. I really do not understand what is happening in
my system.

**Comment by eguvep** [comment]
You mean the »Permission denied« error and the strange path generation?
Can you open a Terminal or IDLE and check, whether `getcwd` returns a proper path?
On Windows, it should look like in the screenshot, with escaped backslashes:
![Bildschirmfoto von 2021-02-28 07-15-57](https://user-images.githubusercontent.com/58531020/109409713-4df63080-7995-11eb-8756-81e66bca103c.png)

**Comment by PAMPA-1996** [comment]
Yes,I checked it. I am using Anaconda for openpivgui.

**Comment by eguvep** [comment]
I just found out, that your path is perfectly valid!
![Bildschirmfoto von 2021-02-28 08-16-31](https://user-images.githubusercontent.com/58531020/109410742-6b2efd00-799d-11eb-8554-bc54b7d14e89.png)
You can use slashes on Windows and even mix them with escaped backslashes (like in your example). Python is so smart ;-)
So I suppose, you really do not have write permisson for the destination directory. So I think, I can close this issue, right?

**Comment by PAMPA-1996** [comment]
Thanks a lot.

Now it is working properly.

**Comment by eguvep** [comment]
Fine! I am very happy to hear that!
