### ISSUE TITLE
openpivgui is misordering images

### ISSUE THREAD

**Issue by weertman** [OpenPIV/openpiv_tk_gui#35]
We have been attempting to get the openpivgui to work on images named 0 - 10 it is misordering them. the order is being changed to 0,1,10,2,3,4,5,6,7,8,9

how does openpivgui expect the images to be ordered?

**Comment by ErichZimmer** [comment]
Please give an example for testing and steps to reproduce. The GUI is supposed to work in alphabetical order.

**Comment by alexlib** [comment]
I guess we need to add something like: 

```
import glob
import re

files = glob.glob1(img_folder,'*'+output_image_format)

# Sort files according to the digits included in the filename
files = sorted(files, key=lambda x:float(re.findall("(\d+)",x)[0]))
```

from https://stackoverflow.com/questions/4623446/how-do-you-sort-files-numerically

**Comment by weertman** [comment]
We have now figured out the ordering. We wrote a python script to change the names of our images so they will sort alphabetically. Sorry for taking so long to respond. Unfortunately, this error popped up during a group work session when we were trying to figure out OpenPIV and we failed to take any screenshots of the error. 

We had a weird bug where the reset session button was not clearing the memory of the GUI. We would reset session import images run processing and then all of a sudden all the images in the directory would be imported. Now we just reset the session and exit between all processing steps, seems to be a workaround to the issue. 

You would happen to know what would cause this error?

```
Processed image pair: 480
Process time: 1.559 second(s)
Number of vectors: 869
Time per vector: 1.794 millisecond(s)
Starting validation. Please wait for validation to finish
Postprocessing thread stopped. filter footprint array has incorrect shape.
```

We process our image pairs but cannot post-process the pairs with the GUI. I cannot figure out what the ```filter footprint array```is. 

Thank you! fun to see you on GitHub @alexlib I enjoyed the ~1hr YouTube video you shared on OpenPIV

**Comment by eguvep** [comment]
Alphabetic order: I recommend to use leading zeros. In this case, numbered files are correctly ordered in all programmes (file-explorer, terminal, ...), not only the OpenPiv GUI.

Memory reset: The GUI does not really import or hold the files in memory. It just displays a filtered list of files of the current working directory. Changing the working directory, also changes the displayed list of image or vector files (depending on the current filter, that can be changed with the arrow buttons below the file-list).

Incorrect shape of filter footprint array: There seems to be a bug in the median filter. Post Processing works for me, if I disable median filtering. The error is raised here: https://github.com/scipy/scipy/blob/47af6102fc5a900c5008bc4ad8415ad2a136c92c/scipy/ndimage/_filters.py#L1593
@alexlib : Is the following line in validation.py correct? https://github.com/OpenPIV/openpiv-python/blob/f71ddb8ae410d9dff5c31d48d98f528fbd37e3f7/openpiv/validation.py#L255

**Comment by alexlib** [comment]
The line seems to be correct. Size=1 creates a 3 x 3 filter kernel, ie 8 Neighbours

**Comment by eguvep** [comment]
I can reproduce the error without GUI:

```
from openpiv.validation import local_median_val
from numpy import loadtxt

data = loadtxt('tst.txt') 
local_median_val(data[:, 2], data[:, 3], 1.2, 1.2)
```
gives: RuntimeError: filter footprint array has incorrect shape.

Do you have a clue, what is wrong with this code, @alexlib ?
[tst.txt](https://github.com/OpenPIV/openpiv_tk_gui/files/6899703/tst.txt)

I attached the test-data.

**Comment by eguvep** [comment]
My mistake – sorry! We have to do
```
from openpiv.validation import local_median_val
from numpy import loadtxt
from numpy import reshape
from open_piv_gui_tools import get_dim

data = loadtxt('tst.txt')
shape = get_dim(data)
local_median_val(
    reshape(data[:, 2], shape),
    reshape(data[:, 3], shape),
    1.2, 1.2)
```
I will correct that with the next version v.4.4.6 in a few minutes.
