### ISSUE TITLE
Use of synthetic images for OpenPIV-python notebook examples

### ISSUE THREAD

**Issue by ErichZimmer** [OpenPIV/openpiv_tk_gui#37]
Dear Peter,

May I use your synthetic image examples on this repository for an example of how to use rectangular windows using the `windef` script? With the new `sliding_window_array` function, rectangular windows are now possible. Additionally, vectorized functions were added to speed up OpenPIV-python evaluations. For a demonstration of these new functions, I think your synthetic images would work pretty good due to its relatively high displacements in the x-axis.
![single_pass_windef](https://user-images.githubusercontent.com/69478071/132116078-fa339704-0aac-4fc1-8d2c-4eab00248961.png)

Regards,
Erich

**Comment by eguvep** [comment]
Yes, of course! 
That is a useful feature! We use JPIV at the moment to derive shear-stress information in the boundary layer, because we can use rectangular windows there.

**Comment by ErichZimmer** [comment]
Link to pull request with above stated features: https://github.com/OpenPIV/openpiv-python/pull/212
