### ISSUE TITLE
new error 

### ISSUE THREAD

**Issue by alexlib** [OpenPIV/openpiv_tk_gui#4]
`Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/alexliberzon/miniconda3/envs/openpiv-tk/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "OpenPivGui.py", line 124, in start_processing
    PostProcessing(self.p).sig2noise())
  File "/Users/alexliberzon/miniconda3/envs/openpiv-tk/lib/python3.7/site-packages/openpivgui/PostProcessing.py", line 48, in sig2noise
    data = np.loadtxt(f)
  File "/Users/alexliberzon/miniconda3/envs/openpiv-tk/lib/python3.7/site-packages/numpy/lib/npyio.py", line 1112, in loadtxt
    first_line = next(fh)
  File "/Users/alexliberzon/miniconda3/envs/openpiv-tk/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 85: invalid start byte`

**Comment by alexlib** [comment]
@eguvep not sure where the problem is - I think I tested it on the same set of images before, but I had to reinstall Python and now it shows this. 
The strange thing is that it happens when i do `start processing` on your test images and it seems that the `np.loadtxt(f)` tries to read the images, which is completely strange.

**Comment by eguvep** [comment]
Dear @alexlib ! Your description sounds like a post processing attempt on image data. This happens, when »direct correlation« on the »PIV« settings rider is unchecked.

**Comment by alexlib** [comment]
@eguvep probably i misinterpreted 'checking' the direct correlation. doesn't it mean a switch between FFT-based and direct- correlations? 
these are people that never read the manuals :)

**Comment by eguvep** [comment]
As soon as a second method is implemented, the check box can be used to select one method – or more, for comparison. For now, it switches the PIV evaluation off. This is useful in case you already have vector data as input, and just want to perform validation and post-processing. For the moment, I resigned on programming any kind of checks, if the input data or the combination of options is meaningful, to keep the code as clean and as simple as possible to lower the hurdle for contributions.
