### ISSUE TITLE
extension to enable file sequence processing? 

### ISSUE THREAD

**Issue by alexlib** [OpenPIV/openpiv_tk_gui#5]
Hi @eguvep - I'm not sure how to process long sequence if I want to have 1->2, 2->3, ... and so on and how to process the same list with the 1->2 , 3 -> 4 (this seems to be a default one, right) or to have a "larger jump", i.e. 1->5, 2->6, ... is it possible?

**Comment by eguvep** [comment]
Dear @alexlib! 
Yes, this would certainly be a useful feature. I implemented that, and a few more combinations in JPIV:
https://eguvep.github.io/jpiv/settings_piv_general.html
In OpenPivGui, you need workarounds for the moment. Some I can think of are:
- Click »select files« and use the Ctrl-key to select only the images you want to process. 
- You may use a regular expression (navigation pattern on general tab). For example, having numbered files in pgm format, the pattern [02468].pgm$ will select only even files.
- Use any other tool or script to generate a subset of image files outside OpenPivGui and copy them into a separate directory for processing them with OpenPivGui.
