### ISSUE TITLE
problem installing from the source

### ISSUE THREAD

**Issue by erfanhamdi** [OpenPIV/openpiv_tk_gui#50]
Hey there

I have tried to clone and install it from the source but I get some errors like 
```
_tkinter.TclError: couldn't recognize data in image file ".../openpiv_tk_gui/openpivgui/res/icon.png"
```
after commenting out the line for the icon I just get black screen like this
<img width="1146" alt="Screen Shot 2022-06-29 at 1 40 09 PM" src="https://user-images.githubusercontent.com/30288548/176398964-6defec99-9cad-414f-80a7-233656e50fd4.png">

**Comment by alexlib** [comment]
do you use Windows?

**Comment by erfanhamdi** [comment]
> 

no it is macos 12.4

**Comment by alexlib** [comment]
@eguvep - do you have an access to macos 12.4 to test it?

**Comment by erfanhamdi** [comment]
seems like the problem was with the tkinter and Python 3.8.9. upgraded to python 3.10.5 and now it is working fine.
