### ISSUE TITLE
Numpy deprecated alias: `np.int` was a deprecated alias for the builtin `int`.

### ISSUE THREAD

**Issue by bmazinng** [OpenPIV/openpiv_tk_gui#52]
Hi,
I was just exploring your nice looking OpenPIV solution! Let me in advance thank you for your contribution to PIV analysis in python. While exploring i have found typical error these days, after latest numpy update np variables are deprecated and code that uses them does not work properly. Users might be able to go around this by "downgrading" numpy before 1.20 version, but to solve this it might be necessary to change all the np.variables to standard built-in python variables.

To replicate this issue, I did this:

>> pip3 install openpivgui
>> python3 -m openpivgui.OpenPivGui
I opened 2 images in GUI using File > Import Files
I hit "start preprocessing" button

![np variables](https://user-images.githubusercontent.com/54368556/222686846-e96f1415-250e-4ae4-bc7a-35ea8a965ffe.jpg)

**Comment by alexlib** [comment]
@bmazinng which Python and Numpy versions do you use? 
@eguvep - could we please get 0.25.0 version into GUI and jointly move to Numpy 1.24 ?

**Comment by eguvep** [comment]
Yes, there is no reason to keep the deprecated variables – except of spare time for programming. Please, @bmazinng, feel free to update the GUI and start a pull request. If not, I keep this issue open and return to that maybe in May.

**Comment by dnowacki-usgs** [comment]
This error derives from a call in smoothn.py in openpiv-python. I submitted a [PR over there](https://github.com/OpenPIV/openpiv-python/pull/292) to change `np.int` to `int`.

**Comment by alexlib** [comment]
> This error derives from a call in smoothn.py in openpiv-python. I submitted a [PR over there](https://github.com/OpenPIV/openpiv-python/pull/292) to change `np.int` to `int`.

thanks @dnowacki-usgs  - I'll pull the request. The problem is that the GUI is still using an older version of OpenPIV (0.23.8) and  this leads to incompatibility. you can either install older version of openpiv (which works with TK GUI) or help us to update GUI to work with the latest version of OpenPIV. Could you help us, please?
