### ISSUE TITLE
A minor problem with Launch OpenPivGui.

### ISSUE THREAD

**Issue by BaseBlank** [OpenPIV/openpiv_tk_gui#56]
I am installing openpivgui in my virtual environment in Anaconda and I am typing commands in Anaconda Prompt , I have python version 3.11 in my virtual environment.
But I am not able to start the GUI program when I enter the following command.
`python3 -m openpivgui.OpenPivGui`
I modified it to the following command and I can start the GUI program normally.
`python -m openpivgui.OpenPivGui`
I hope to give feedback to the project development members in time.

In my virtual environment:
pip list:
Package            Version
------------------ ------------
asttokens          2.4.1
colorama           0.4.6
contourpy          1.2.0
cycler             0.12.1
decorator          5.1.1
executing          2.0.1
filelock           3.9.0
fonttools          4.49.0
fsspec             2023.4.0
gitdb              4.0.11
GitPython          3.1.42
imageio            2.34.0
importlib-metadata 7.0.1
iniconfig          2.0.0
ipython            8.22.1
jedi               0.19.1
Jinja2             3.1.2
kiwisolver         1.4.5
lazy_loader        0.3
MarkupSafe         2.1.3
matplotlib         3.8.3
matplotlib-inline  0.1.6
mpmath             1.3.0
natsort            8.4.0
networkx           3.2.1
numpy              1.26.4
opencv-python      4.9.0.80
OpenPIV            0.23.8
openpivgui         0.4.14
packaging          23.2
pandas             2.2.1
parso              0.8.3
pillow             10.2.0
pip                23.3.1
pluggy             1.4.0
prompt-toolkit     3.0.43
pure-eval          0.2.2
Pygments           2.17.2
pyparsing          3.1.1
pytest             8.0.2
python-dateutil    2.9.0.post0
pytz               2024.1
scikit-image       0.22.0
scipy              1.12.0
setuptools         68.2.2
six                1.16.0
smmap              5.0.1
stack-data         0.6.3
sympy              1.12
tifffile           2024.2.12
torch              2.2.1+cu121
torchaudio         2.2.1+cu121
torchvision        0.17.1+cu121
tqdm               4.66.2
traitlets          5.14.1
typing_extensions  4.8.0
tzdata             2024.1
watermark          2.4.3
wcwidth            0.2.13
wheel              0.41.2
zipp               3.17.0

**Comment by eguvep** [comment]
Thank you for this hint, @BaseBlank,
Depending on the local system location, one may use pip3 or pip and python3 or python. I added this Information to the README file.
