### ISSUE TITLE
Error while executing with conda env.

### ISSUE THREAD

**Issue by ErichZimmer** [OpenPIV/openpiv_tk_gui#6]
Hi,
I recently installed OpenPIV GUI via pip3 and pip, but I can't seem to get the GUI to execute. I use miniconda with all the dependencies for PivPy, OpenPIV, and the GUI installed and maybe miniconda itself could possibly be the source of the error. If I go into the folder where the openpivgui was installed and run OpenPivGui with idle 3.8, I get an error saying "no module named "OpenPivGui"". If I try to execute it from the conda prompt, either nothing happens (for pip3) or an error occurs (for pip). I use windows 10 and python 3.8.5.

![OpenPivGui_Error](https://user-images.githubusercontent.com/69478071/90716606-fbfc8180-e272-11ea-8689-4260db57d808.PNG)

**Comment by alexlib** [comment]
@ErichZimmer I do not know the command `conda run`, please use:

`conda activate _name_of_your_environment_`
`python OpenPivGui.py`

**Comment by ErichZimmer** [comment]
Hi, sorry to bother you again.

I tried the following and I get "error on line 675, "HOME"". When testing the program in Jupyter Lab, the error occurred at line 675 just like the conda promot and highlighted 
" openPivGui = OpenPivGui()
OpenPivGui.mainloop()" 
With the error "HOME". I wonder if I should uninstall everything and reinstall everything again? Sorry for my naiveness, I hit a wall in my troubleshooting.
For repeatability (if deemed necessary), I used miniconda and installed everything like the following,
>Conda install -c conda-forge openpiv, jupyterlab, ipywidgets
>Pip install pivpy, nose, streamlit

**Comment by alexlib** [comment]
I think it has to run from a command line. Depends on your setup, open Anaconda command prompt and try to run the GUI from there with the commands above. 
There is a video from the developer that explains how to run this GUI.

**Comment by ErichZimmer** [comment]
I watched the video some dozen times and installed the GUI various ways, but I keep getting the same error. It seems like it's not the GUI, but it is runpy.py that is the problem. I searched online for ways to get runpy.py to work when executing the GUI, but they did not work so far. The problems I'm getting are most likely user error of some sort, so I'll have to dig deeper into what I possibly did wrong.

Edit: 
I tried debugging by creating several conda environments with various installation methods of the dependencies, but they all got the same error. This could be a conda windows 10 thing.

**Comment by alexlib** [comment]
Seems like a corrupted miniconda installation. I would remove miniconda and start over.
- Miniconda for Python 3
- new environment 
- Openpiv GUI is installed with **pip** in the new environment. It should automatically pull all the requirements including openpiv 

@eguvep Do you think there is something else ?

**Comment by eguvep** [comment]
Dear ErichZimmer,

Is the following command working?

`python3 -m openpivgui.OpenPivGui`

What is the detailed error message? Just »Home«?

**Comment by eguvep** [comment]
Sorry, just saw, you tried that and posted it above.
What happens, if you change into the installation directory, where OpenPivGui.py resides and execude 'python3 ./OpenPivGui.py'?
Alex solution with the new environment is smarter, however.

**Comment by eguvep** [comment]
Probably worth trying is to add the installation folder of OpenPivGui to the python path. A web search showed, that there are a couple of ways to do so permanently or temporarily under Windows. I am solely on Linux, though, and can not verify that.

**Comment by ErichZimmer** [comment]
@alexlib I tried your instructions and got the same errors. Here is what I did so far.
-Reinstalled python 3.8.5
-Reinstalled miniconda 3.8.3 (latest stable version)

In conda, I created three different environments called 'PipPIV', 'CondaPIV', and 'OpenPIV'. All of which have python set to 3.8.5.

For PipPIV env.:
>pip install openpivgui

For CondaPIV env.:
>conda install -c conda-forge openpiv
>pip install openpivgui

For OpenPIV env. (for experimenting/analysing):
>conda install -c conda-forge openpiv, jupyterlab, ipywidgets, voila
>pip install openpivgui, pivpy, streamlit


All three environments got the same error. If I run '>conda run OpenPivGui.py' with an extended directory via conda '>cd' command, I get a new error saying that openpiv.tools and module openpiv can't be found.

@eguvep I wasn't able to try your suggestions yet, but I did something similar by adding miniconda, the conda env, site-packages, openpiv, and openpivgui to path and it didn't seem to do much (I haven't added them all at the same time though, just individually). I'll look into your suggestion later today though.

**Comment by alexlib** [comment]
Send me by email the teamviewer ID and pass and the time slot when the computer is connected. I will try to look at it closely 
Alex

**Comment by alexlib** [comment]
Two things are strange to me :
1. You don't need to install python before miniconda. Miniconda has its own python and it is definitely different from the Windows one. 
2. I don't know conda run command. I use always only the following

conda activate openpiv
(Openpiv) python ./OpenPivGui.py

**Comment by ErichZimmer** [comment]
I'll install TeamViewer once I get access to a mobile hotspot and I'll see if I can't get it setup for remote access today or the day after tomorrow.

Meanwhile, should I uninstall miniconda and python and reinstall miniconda with it's python version? I know you can update the python version, but I downloaded python 3.8.5 because miniconda's latest python version is 3.8.3 and I was a little worried about some stuff, notably of which is tkinter.

**Comment by alexlib** [comment]
1. Miniconda or Windows Python with pip - both options are fine, but not both at the same time. If you are using miniconda, then you don't need to install python before or separately from it. The problem is that they might interfere and you might not always know which one is active
2. If you use Miniconda, Python 3.8.3 is fine, no problem. They update Python as soon as other things work well. And you get most of what's needed there. If you want the latest Python, then stick to PYthon + virtual environments.

**Comment by eguvep** [comment]
Was OpenPivGui correctly installed into the site-packages folder? This should be something like »...anaconda3/lib/python3.7/site-packages/openpivgui«. On our laboratory Windows computer everything works fine with anaconda installed first and then OpenPivGui installed with pip3. Anaconda should be aware of pip packages. We can not reproduce the error.

**Comment by alexlib** [comment]
I also installed it on Mac OS X from scratch and it works.

**Comment by ErichZimmer** [comment]
Dear OpenPIV team,

Thank you for all your help and suggestions so far. I uninstalled everything again and installed miniconda only, but I did not add it to PATH as someone told me not to. For the conda environments, I created two for testing. The first one is 'PipPIV' which had everything installed using 'pip install openpivgui'. The second environment was for personal use and OpenPIV was installed via conda-forge and some other stuff listed on my earlier posts. I still got the same errors, so I am still kind of lost. I think it might be something to deal with PATH, but I'm too naive at my current state of education to know for sure.

As for TeamViewer, I got permission to install it (not my laptop), but anything requiring administrative powers are not allowed unless supervised.

**Comment by eguvep** [comment]
If everything fails, there is still the (not very smart, but almost failsafe) option to download the six *.py files from https://github.com/OpenPIV/openpiv_tk_gui/tree/master/openpivgui, change into the download directory and execute 'python3 OpenPivGui.py'. This option still requires, that OpenPIV can be found by python3. I keep this issue open for now: Possibly there are other conda users with a similar problem or a solution. We will also discuss, if it is helpful to upload OpenPivGui to the conda repositories, additionally to pypi.

**Comment by eguvep** [comment]
We were now able to reproduce the error on another windows computer and fixed it. Please use 'pip3 install --upgrade openpivgui' to get the latest version (0.1.13).
Background: 'os.environ["HOME"]' seems to fail on (some?) Windows platforms. We replaced it by 'os.path.expanduser()'. We need this to find the settings file, which is stored in the users home directory. We tested this on Windows 10 and Ubuntu Linux 18.04. I hope, this works on Apple, too.
I apologize, not to have recognized the error message correctly the first time.

**Comment by alexlib** [comment]
an updated version installs well on Mac OS X. Thanks for the fix

**Comment by eguvep** [comment]
Thanks for testing, Alex!
